version: "3"

services:

  server:
    image: postgres:15.3
    container_name: server
    environment:
      POSTGRES_PASSWORD: docker_postgres
      POSTGRES_USER: docker_postgres
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5433:5432"
    networks:
      pg_net:
        ipv4_address: "192.168.54.2"

  client:
    image: postgres:15.3
    container_name: client
    depends_on:
      - server
    networks:
      pg_net:
        ipv4_address: "192.168.54.3"

networks:
  pg_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.54.0/29"
